# Generated by Django 4.2.17 on 2024-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Kolaydegildir123.', max_length=128),
        ),
    ]
